@startuml

Abstraction o-- Implementor

abstract class Abstraction {
  #Implementor

  #Abstraction(Implementor impl)
  +void feature()
}

class RefinedAbstraction extends Abstraction {
  #Implementor

  #RefinedAbstraction(Implementor impl)
  +void feature()
}

interface Implementor {
  +void method()
}

class ConcreteImplementorA implements Implementor {
  +void method()
}

class ConcreteImplementorB implements Implementor {
  +void method()
}

@enduml