@startuml

AbstractFactory *-- ProductA
AbstractFactory *-- ProductB

interface ProductA {
  +void operationA()
}

class ConcreteProductA1 implements ProductA {
  +void operationA()
}

class ConcreteProductA2 implements ProductA {
  +void operationA()
}

interface ProductB {
  +void operationB()
}

class ConcreteProductB1 implements ProductB {
  +void operationB()
}

class ConcreteProductB2 implements ProductB {
  +void operationB()
}

interface AbstractFactory {
  +ProductA createProductA()
  +ProductB createProductB()
}

class ConcreteFactory1 implements AbstractFactory {
  +ProductA createProductA()
  +ProductB createProductB()
}

class ConcreteFactory2 implements AbstractFactory {
  +ProductA createProductA()
  +ProductB createProductB()
}
@enduml