@startuml

Client *-- ConcretePrototype

interface Prototype {
  +Prototype clone()
}

class ConcretePrototype implements Prototype {
  +ConcretePrototype clone()
}

class Client {
  -ConcretePrototype concretePrototype
}

@enduml