@startuml

interface Prototype {
  +Prototype clone()
}

class ConcretePrototype implements Prototype {
  +ConcretePrototype clone()
}

class Client {
  -ConcretePrototype concretePrototype
}
Client --> ConcretePrototype

@enduml