@startuml

Adapter o-- Adaptee

class Adaptee {
  +void operation()
}

interface Target {
  +void operation()
}

class Adapter implements Target {
  -Adaptee adaptee

  +Adapter(Adaptee adaptee)
  +void operation()
}

@enduml