@startuml

AbstractFactory *-- Product

interface Product {
  +void operation()
}

class ConcreteProductA implements Product {
  +void operation()
}

class ConcreteProductB implements Product {
  +void operation()
}

interface AbstractFactory {
  +Product createProduct()
}

class ConcreteFactoryA implements AbstractFactory {
  +Product createProduct()
}

class ConcreteFactoryB implements AbstractFactory {
  +Product createProduct()
}

@enduml