@startuml

SimpleFactory *-- Product

interface Product {
  +void operation()
}

class ConcreteProductA implements Product {
  +void operation()
}

class ConcreteProductB implements Product {
  +void operation()
}

class SimpleFactory {
  +Product createProduce()
}

@enduml